### ISSUE TITLE
No payment sheet is shown [BUG]

### ISSUE THREAD

**Issue by azizgenz** [superwall-me/Superwall-iOS#112]
## New issue checklist
- [Yes] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [Yes] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [Yes] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version: 2.5.8
- iOS version(s): 14.2
- CocoaPods/Carthage version (if applicable):
- Xcode version: 14.2

### Describe the bug

I get a prompt saying "Waiting to purchase..." with a description "Your connection maybe offline. Waiting for transaction to begin...". And there's no payment sheet presented. I'm using SwityStoreKit directly and when i use that, it works just fine. The paywall loads all the info of the product, everything works fine, it's just when i tap the purchase button, it shows that prompt and hangs there...

### Steps to reproduce
Tapping the purchase button

**Comment by yusuftor** [comment]
Can you confirm whether you’re using StoreKit 1 or 2? This can happen in StoreKit 2 which is unsupported in v2 of the SDK.

And can you show your code for purchasing?
