### ISSUE TITLE
[BUG] SwiftUI Sample App Blocking Bug, Paywall Not Displayed when Purchase Controller Implemented

### ISSUE THREAD

**Issue by seth35us** [superwall-me/Superwall-iOS#118]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version: 3.0.0-beta.8
- iOS version(s): 16.3.1
- CocoaPods/Carthage version (if applicable):
- Xcode version: 14.2
- Devices/Simulators affected: iPhone 13
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

### Describe the bug
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

- Paywall not displayed with `Superwall.shared.track(event: "campaign_trigger") ` if `purchaseController: shared` enabled on initial install. 

### Steps to reproduce
Please also include a description of expected vs. actual behaviour

1. Uncomment code in SwiftUI sample project to enable the purchaseController. 
2. From a fresh install click the "Track event" button. 
    - Expected, a paywall will display
    - Actual, no paywall is displayed 

### Other Information
e.g. stacktraces, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.

**Comment by jakemor** [comment]
Most likely `Superwall.shared.subscriptionState` is `.unknown` – can you confirm you uncommented the following in `SuperwallService.swift`?

```swift
27  Task {
28    await StoreKitService.shared.loadSubscriptionState()
29  }
```

If you decide to manage purchasing on your own, you also must make sure this value is kept up to date

**Comment by seth35us** [comment]
You are correct, I was missing that code, and I am super embarrassed. This was really well documented in retrospect. Sorry for the non-issue.
