### ISSUE TITLE
[BUG] Superwall.configure throws errors

### ISSUE THREAD

**Issue by lewis-smith** [superwall-me/Superwall-iOS#121]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version: 3.0.0-rc.1
- iOS version(s): 16.4
- CocoaPods/Carthage version (if applicable): n/a
- Xcode version: 14.3
- Devices/Simulators affected: device and sim
- Reproducible in the demo project? (Yes/No): yes
- Related issues: n/a

### Describe the bug
There is recursion bug in the configure method where it tries to inspect `.superwall` before it's finished being set.

You can see many instances of `‼️ [Superwall] [superwallCore] ERROR: Superwall has not been configured. Please call Superwall.configure()` in the logs

### Steps to reproduce
- create blank project
- add Superwall dependency
- call `Superwall.configure(apiKey: "MYAPIKEY")` in `application(didFinishLaunchingWithOptions..)`
- See errors `‼️ [Superwall] [superwallCore] ERROR: Superwall has not been configured. Please call Superwall.configure()`
- If setting a purchase controller it may not be saved

### Other Information
Add a breakpoint at Superwall.swift, line 139 to see what's happening
<img width="1006" alt="CleanShot 2023-04-07 at 12 20 09@2x" src="https://user-images.githubusercontent.com/1905433/230600448-30c7e3bf-47c3-4b97-b06d-fb15fa99f777.png">

Demo project. Unzip and run to see errors
[Superwall Test.zip](https://github.com/superwall-me/Superwall-iOS/files/11178479/Superwall.Test.zip)

**Comment by super-bryan** [comment]
Hey @lewis-smith! Thanks for reporting this – we're pushing up a fix now.

**Comment by Turacbey** [comment]
@super-bryan 
Heyy, when will it be available?

**Comment by jakemor** [comment]
This is fixed in `3.0.0-rc.2` :)

**Comment by Turacbey** [comment]
@jakemor 
Thank you :-)
