### ISSUE TITLE
[BUG] When the device doesn't have connectivity, calls to Superwall.shared.register(...) fail silently, and no further paywalls are shown even after gaining the connection

### ISSUE THREAD

**Issue by tkafka** [superwall-me/Superwall-iOS#135]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version: 3.0.0. rc6
- iOS version(s): 16.4
- CocoaPods/Carthage version (if applicable):
- Xcode version: 13.4
- Devices/Simulators affected: All
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Describe the bug
I am moving to 3.0.0 SDK on iOS, and I noticed that when the device doesn't have connectivity, call to `Superwall.shared.register(...)` fails silently.

I was expecting handler.onError to be called. I have a fallback native paywall, and I wanted to display in this case, or at least show an error message about the need to connect to internet unlock the paid features.

### Steps to reproduce
```swift
let handler = PaywallPresentationHandler()
		handler.onPresent { paywallInfo in
			self.isShowingSuperwall = true
			// PaywallService.registerMostRecentWindowState(windowState)
			PermanentLogger.logBoth("Trigger paywall \(paywallInfo.identifier)")
		}
		handler.onDismiss { paywallInfo in
			self.isShowingSuperwall = false
			switch paywallInfo.closeReason {
			case .forNextPaywall:
				PermanentLogger.logBoth("Trigger paywall: Paywall closed for the next paywall.")
			case .systemLogic:
				PermanentLogger.logBoth("Trigger paywall: Paywall closed because of system logic (either after a purchase, because a deeplink was presented, close button pressed ...).")
			case .none:
				PermanentLogger.logBoth("Trigger paywall: Paywall closed, no reason.")
			}
		}
		handler.onError { error in
			self.isShowingSuperwall = false
			PermanentLogger.logBoth("Trigger paywall: Did fail, error=\(error.messageAndCode)")
			/// and show fallback
			fallbackPaywall()
		}
		handler.onSkip { reason in
			self.isShowingSuperwall = false
			switch reason {
			case .userIsSubscribed:
				print("Paywall not shown because user is subscribed.")
			case let .holdout(experiment):
				print("Paywall not shown because user is in a holdout group in Experiment: \(experiment.id)")
			case .noRuleMatch:
				print("Paywall not shown because user doesn't match any rules.")
			case .eventNotFound:
				print("Paywall not shown because this event isn't part of a campaign.")
			}
			if force {
				/// show fallback
				fallbackPaywall()
			}
		}

		Superwall.shared.register(event: "open_paywall_user_initiated", handler: handler)
```

1. Turn off the paywall preload (`superwallOptions.paywalls.shouldPreload = false`)
2. Disconnect the device from the internet
3. Try to show the paywall - it doesn't get displayed, and `handler.onError` isn't called
4. Connect back to the internet
5. Try to show the paywall again (calling the above code)
6. The paywall will not show either, and will not show until the app is killed and restarted

### Other Information
Debugging this with the internet off, I can see the publisher inside `internallyRegister` called (https://github.com/superwall-me/Superwall-iOS/blob/05b04f6beb57c78b1fda5dd3f3e39d0fe15c12cc/Sources/SuperwallKit/Paywall/Presentation/PublicPresentation.swift#L117), but its `receiveValue` handler is NOT called without connection, despite looking like it handles the no connection case (`case .presentationError(...)` )

I believe that this might be a bug, and I expected the `.presentationError` handler to be called.

Even worse, once I try first opening the paywall without internet connection (and it of course fails to open), the subsequent attempts fail as well, even if the connection is re-enabled (I have turned off paywall preload to save user's mobile data).
So, if the user doesn't have internet during the initial paywall load, she will neither get an error message, nor will she see the paywall again until she restarts the app.
Could you look into improving this scenario please? Ideally, I would like to know about the error, and to have the second .register call succeed once the device is back online.

**Comment by yusuftor** [comment]
Hey, the reason why this fails is because the initial call to get your configuration from our server fails and so the paywalls are stuck waiting for config. Then when the internet reconnects it’s not reattempting to get the config so you’re stuck indefinitely. We’re aware of this, and will definitely tackle this issue!

**Comment by yusuftor** [comment]
Also thanks for the detailed bug report, much appreciated!

**Comment by yusuftor** [comment]
This is now fixed in the `develop` branch so closing this issue.

**Comment by tkafka** [comment]
@yusuftor Awesome, thanks! The earlier you can get it to RC, the better, I have just released an app update with RC6 :)
