### ISSUE TITLE
[BUG] Crash when showing deep link preview

### ISSUE THREAD

**Issue by Finnvoor** [superwall-me/Superwall-iOS#138]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue

### General information

- `Superwall` version: `Superwall-iOS 3.0.0-rc.7`
- iOS version(s): `16.6`
- Xcode version: `14.3.1`

### Describe the bug
When scanning the paywall preview QR code the app crashes when presenting `DebugViewController`.

Crash: `SuperwallKit/PaywallViewController.swift:636: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`

`paywallStateSubject` is nil because `set(request: PresentationRequest, paywallStatePublisher: PassthroughSubject<PaywallState, Never>)` is never called on `PaywallViewController` when showing in the debugger.

**Comment by yusuftor** [comment]
Is this definitely happening in rc7? I believe I fixed this

**Comment by Finnvoor** [comment]
I reset package caches, made sure Xcode said it was using rc7, and double checked before opening this ticket, but just went and cleared all derived data + caches and tried again and it seems to be working now, so I guess I just had rc6 cached somewhere… sorry!
