### ISSUE TITLE
[BUG] "Stored properties cannot be marked unavailable with '@available'" in Xcode 15 beta

### ISSUE THREAD

**Issue by tkafka** [superwall-me/Superwall-iOS#143]
These two locations in the code fail to compile under Xcode 15 beta 1:

`Stored properties cannot be marked unavailable with '@available'`
https://github.com/superwall-me/Superwall-iOS/blob/d89049bbb6fcd7aaa93bfd486b3fbda9f7c3cb59/Sources/SuperwallKit/Paywall/Presentation/PaywallInfo.swift#L19

`Stored properties cannot be marked unavailable with '@available'`
https://github.com/superwall-me/Superwall-iOS/blob/d89049bbb6fcd7aaa93bfd486b3fbda9f7c3cb59/Sources/SuperwallKit/Analytics/Superwall%20Event/SuperwallEventInfo.swift#L18

**Comment by tkafka** [comment]
Here's a quick fork with commenting out the problematic attributes (which is of course not the good solution):
https://github.com/tkafka/Superwall-iOS/tree/tk/release-3.0.1-fix-xcode-15

**Comment by yusuftor** [comment]
Thanks for this. The `develop` branch has a fix for this now and will be released with the next version of Superwall. I'll leave this issue open until that gets merged to master.

**Comment by yusuftor** [comment]
Released in 3.0.2!
