### ISSUE TITLE
Flutter integration

### ISSUE THREAD

**Issue by simplenotezy** [superwall-me/Superwall-iOS#175]
I'd love a flutter integration. Or alternatively a way to integrate it into any codebase, given it's a simple webkit wrapper.

**Comment by flodaniel** [comment]
Just came here to check if there is a roadmap for a flutter plugin/wrapper :)

**Comment by yusuftor** [comment]
Hey, currently we're concentrating on the launch of the Android SDK and we'll be starting on wrappers like Flutter after launching this. Some people in the community did create a React Native wrapper for Superwall though so we're totally open to community-led open source wrappers in the meantime!
