### ISSUE TITLE
[BUG] Crash in scheduleNotification func

### ISSUE THREAD

**Issue by seth35us** [superwall-me/Superwall-iOS#185]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version:
- iOS version(s):
- CocoaPods/Carthage version (if applicable):
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Describe the bug
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

Crash on these lines of code in the NotificationScheduler: 

 let trigger = UNTimeIntervalNotificationTrigger(
      timeInterval: delay,
      repeats: false
    )

### Steps to reproduce
Please also include a description of expected vs. actual behaviour
1. Add paywall with FreeTrialReminder Notification set to default, which is none. 
2. Make a purchase on that paywall. 
3. Delay is set to an invalid value. 

### Other Information
e.g. stacktraces, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.

**Comment by anglinb** [comment]
Thanks for reporting this issue, we'll add a check there to make sure we don't pass invalid data. I imagine this happened in development, right? We speed up the time intervals when in dev so you can easily test

**Comment by seth35us** [comment]
No, it happened in production. The users got a crash as soon as they made a
purchase. This was the first paywall I implemented that had reminder
notifications turned on by default, and I didn’t notice it right away.

I disabled the paywall until I could figure out what happened.

I payed for several test purchases using Superwall to isolate the issue.

**Comment by yusuftor** [comment]
Hey @seth35us, when you say this:

> Add paywall with FreeTrialReminder Notification set to default, which is none.

Do you mean it's set like this, with no free trial reminder?

<img width="392" alt="Screenshot 2023-11-20 at 19 28 47" src="https://github.com/superwall-me/Superwall-iOS/assets/3296904/108013cd-55e6-4ef4-ba9e-44d0066e1305">


Or do you mean like this, where it defaults to Day 1:

<img width="385" alt="Screenshot 2023-11-20 at 19 31 50" src="https://github.com/superwall-me/Superwall-iOS/assets/3296904/76bfb63d-0658-4465-a420-4da09f80d87a">


Please can you provide a link to your paywall that you have issues with and a stack trace of the error so I can try and reproduce? Thanks!

**Comment by seth35us** [comment]
It was set to default to Day 1. It stopped crashing when I removed the free
trial reminder.

Here is a link to the paywall:
https://superwall.com/applications/1822/paywalls/13500/v3

**Comment by seth35us** [comment]
Here is a stack trace.

# Crashlytics - Stack trace # Application: com.astrumcomputing.cleaner #
Platform: apple # Version: 1.0.21 (22) # Issue:
e361d922cb4d1552b548178694260835 # Session:
ddb554257349405ab3df3aaeaf5ef5bd_DNE_0_v2 # Date: Wed Nov 15 2023 08:39:11
GMT-0700 (Mountain Standard Time) Fatal Exception:
NSInternalInconsistencyException 0 CoreFoundation 0xec870
__exceptionPreprocess 1 libobjc.A.dylib 0x2bc00 objc_exception_throw 2
Foundation 0x6b6d18 _userInfoForFileAndLine 3 UserNotifications 0x82a0
-[UNTimeIntervalNotificationTrigger _initWithTimeInterval:repeats:] 4
UserNotifications 0x8180 +[UNTimeIntervalNotificationTrigger
triggerWithTimeInterval:repeats:] 5
SuperwallKit_-BCC3FC367400D_PackageProduct 0x22148c (1) suspend resume
partial function for specialized static
NotificationScheduler.scheduleNotification(_:factory:notificationCenter:) +
67 (NotificationScheduler.swift:67) 6
SuperwallKit_-BCC3FC367400D_PackageProduct 0x221849 (1) await resume
partial function for closure #1 in closure #1 in static
NotificationScheduler.scheduleNotifications(_:factory:notificationCenter:)
7 SuperwallKit_-BCC3FC367400D_PackageProduct 0x2211e5 (1) await resume
partial function for partial apply for closure #1 in closure #1 in static
NotificationScheduler.scheduleNotifications(_:factory:notificationCenter:)
() 8 SuperwallKit_-BCC3FC367400D_PackageProduct 0x220505 (1) await resume
partial function for specialized thunk for @escaping @callee_guaranteed
@Sendable @async () -> ***@***.*** A) () 9
SuperwallKit_-BCC3FC367400D_PackageProduct 0xc009 (1) await resume partial
function for partial apply for specialized thunk for @escaping
@callee_guaranteed @Sendable @async () -> ***@***.*** A) 10
libswift_Concurrency.dylib 0x49ac5
completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*)
com.apple.main-thread 0 libsystem_kernel.dylib 0x11d8 mach_msg2_trap + 8 1
libsystem_kernel.dylib 0xf70 mach_msg2_internal + 80 2
libsystem_kernel.dylib 0xe88 mach_msg_overwrite + 436 3
libsystem_kernel.dylib 0xcc8 mach_msg + 24 4 CoreFoundation 0x35d0c
__CFRunLoopServiceMachPort + 160 5 CoreFoundation 0x33c04 __CFRunLoopRun +
1208 6 CoreFoundation 0x33668 CFRunLoopRunSpecific + 608 7 GraphicsServices
0x35ec GSEventRunModal + 164 8 UIKitCore 0x22c2b4 -[UIApplication _run] +
888 9 UIKitCore 0x22b8f0 UIApplicationMain + 340 10 SwiftUI 0x11620fc
OUTLINED_FUNCTION_31 + 604 11 SwiftUI 0x1161f40 OUTLINED_FUNCTION_31 + 160
12 SwiftUI 0xdd3868 OUTLINED_FUNCTION_26 + 2196 13 CleanerPlus 0x7a738 main
+ 4296075064 (CleanerPlusApp.swift:4296075064) 14 ??? 0x1cb25adcc (Missing)
com.apple.uikit.eventfetch-thread 0 libsystem_kernel.dylib 0x11d8
mach_msg2_trap + 8 1 libsystem_kernel.dylib 0xf70 mach_msg2_internal + 80 2
libsystem_kernel.dylib 0xe88 mach_msg_overwrite + 436 3
libsystem_kernel.dylib 0xcc8 mach_msg + 24 4 CoreFoundation 0x35d0c
__CFRunLoopServiceMachPort + 160 5 CoreFoundation 0x33c04 __CFRunLoopRun +
1208 6 CoreFoundation 0x33668 CFRunLoopRunSpecific + 608 7 Foundation
0x2c54c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212 8 Foundation
0x5a27c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64 9 UIKitCore 0x18dfc8
-[UIEventFetcher threadMain] + 420 10 Foundation 0xb1184
__NSThread__start__ + 732 11 libsystem_pthread.dylib 0x24d4 _pthread_start
+ 136 12 libsystem_pthread.dylib 0x1a10 thread_start + 8
com.google.firebase.crashlytics.MachExceptionServer 0
libsystem_kernel.dylib 0x11d8 mach_msg2_trap + 8 1 libsystem_kernel.dylib
0xf70 mach_msg2_internal + 80 2 libsystem_kernel.dylib 0xe88
mach_msg_overwrite + 436 3 libsystem_kernel.dylib 0xcc8 mach_msg + 24 4
CleanerPlus 0x168c14 FIRCLSMachExceptionServer + 192
(FIRCLSMachException.c:192) 5 libsystem_pthread.dylib 0x24d4 _pthread_start
+ 136 6 libsystem_pthread.dylib 0x1a10 thread_start + 8
com.apple.NSURLConnectionLoader 0 libsystem_kernel.dylib 0x11d8
mach_msg2_trap + 8 1 libsystem_kernel.dylib 0xf70 mach_msg2_internal + 80 2
libsystem_kernel.dylib 0xe88 mach_msg_overwrite + 436 3
libsystem_kernel.dylib 0xcc8 mach_msg + 24 4 CoreFoundation 0x35d0c
__CFRunLoopServiceMachPort + 160 5 CoreFoundation 0x33c04 __CFRunLoopRun +
1208 6 CoreFoundation 0x33668 CFRunLoopRunSpecific + 608 7 CFNetwork
0x258780 _CFURLStorageSessionCopyIdentifier + 69132 8 Foundation 0xb1184
__NSThread__start__ + 732 9 libsystem_pthread.dylib 0x24d4 _pthread_start +
136 10 libsystem_pthread.dylib 0x1a10 thread_start + 8 H11ANEServicesThread
0 libsystem_kernel.dylib 0x11d8 mach_msg2_trap + 8 1 libsystem_kernel.dylib
0xf70 mach_msg2_internal + 80 2 libsystem_kernel.dylib 0xe88
mach_msg_overwrite + 436 3 libsystem_kernel.dylib 0xcc8 mach_msg + 24 4
CoreFoundation 0x35d0c __CFRunLoopServiceMachPort + 160 5 CoreFoundation
0x33c04 __CFRunLoopRun + 1208 6 CoreFoundation 0x33668 CFRunLoopRunSpecific
+ 608 7 CoreFoundation 0x333cc CFRunLoopRun + 64 8 ANEServices 0xf608
H11ANE::H11ANEServicesThreadStart(H11ANE::H11ANEServicesThreadParams*) +
148 9 libsystem_pthread.dylib 0x24d4 _pthread_start + 136 10
libsystem_pthread.dylib 0x1a10 thread_start + 8 H11ANEServicesThread 0
libsystem_kernel.dylib 0x11d8 mach_msg2_trap + 8 1 libsystem_kernel.dylib
0xf70 mach_msg2_internal + 80 2 libsystem_kernel.dylib 0xe88
mach_msg_overwrite + 436 3 libsystem_kernel.dylib 0xcc8 mach_msg + 24 4
CoreFoundation 0x35d0c __CFRunLoopServiceMachPort + 160 5 CoreFoundation
0x33c04 __CFRunLoopRun + 1208 6 CoreFoundation 0x33668 CFRunLoopRunSpecific
+ 608 7 CoreFoundation 0x333cc CFRunLoopRun + 64 8 ANEServices 0xf608
H11ANE::H11ANEServicesThreadStart(H11ANE::H11ANEServicesThreadParams*) +
148 9 libsystem_pthread.dylib 0x24d4 _pthread_start + 136 10
libsystem_pthread.dylib 0x1a10 thread_start + 8 H11ANEServicesThread 0
libsystem_kernel.dylib 0x11d8 mach_msg2_trap + 8 1 libsystem_kernel.dylib
0xf70 mach_msg2_internal + 80 2 libsystem_kernel.dylib 0xe88
mach_msg_overwrite + 436 3 libsystem_kernel.dylib 0xcc8 mach_msg + 24 4
CoreFoundation 0x35d0c __CFRunLoopServiceMachPort + 160 5 CoreFoundation
0x33c04 __CFRunLoopRun + 1208 6 CoreFoundation 0x33668 CFRunLoopRunSpecific
+ 608 7 CoreFoundation 0x333cc CFRunLoopRun + 64 8 ANEServices 0xf608
H11ANE::H11ANEServicesThreadStart(H11ANE::H11ANEServicesThreadParams*) +
148 9 libsystem_pthread.dylib 0x24d4 _pthread_start + 136 10
libsystem_pthread.dylib 0x1a10 thread_start + 8 Thread 0
libsystem_kernel.dylib 0x9730 __workq_kernreturn + 8 1
libsystem_pthread.dylib 0x19b0 _pthread_wqthread + 364 2
libsystem_pthread.dylib 0x1a04 start_wqthread + 8 Thread 0
libsystem_kernel.dylib 0x9730 __workq_kernreturn + 8 1
libsystem_pthread.dylib 0x19b0 _pthread_wqthread + 364 2
libsystem_pthread.dylib 0x1a04 start_wqthread + 8 Thread 0
libsystem_kernel.dylib 0x9730 __workq_kernreturn + 8 1
libsystem_pthread.dylib 0x19b0 _pthread_wqthread + 364 2
libsystem_pthread.dylib 0x1a04 start_wqthread + 8 Thread 0
libsystem_kernel.dylib 0x9730 __workq_kernreturn + 8 1
libsystem_pthread.dylib 0x19b0 _pthread_wqthread + 364 2
libsystem_pthread.dylib 0x1a04 start_wqthread + 8 Thread 0
libsystem_kernel.dylib 0x9730 __workq_kernreturn + 8 1
libsystem_pthread.dylib 0x19b0 _pthread_wqthread + 364 2
libsystem_pthread.dylib 0x1a04 start_wqthread + 8 JavaScriptCore libpas
scavenger 0 libsystem_kernel.dylib 0x1b7c __psynch_cvwait + 8 1
libsystem_pthread.dylib 0xfd4 _pthread_cond_wait + 1228 2 JavaScriptCore
0x15a4c50 scavenger_thread_main + 1512 3 libsystem_pthread.dylib 0x24d4
_pthread_start + 136 4 libsystem_pthread.dylib 0x1a10 thread_start + 8
Crashed: com.google.firebase.crashlytics.ios.exception 0 CleanerPlus
0x15a7fc FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393) 1
CleanerPlus 0x15abdc FIRCLSProcessRecordAllThreads + 424
(FIRCLSProcess.c:424) 2 CleanerPlus 0x168658 FIRCLSHandler + 34
(FIRCLSHandler.m:34) 3 CleanerPlus 0x1684ac
__FIRCLSExceptionRecord_block_invoke + 232 (FIRCLSException.mm:232) 4
libdispatch.dylib 0x4300 _dispatch_client_callout + 20 5 libdispatch.dylib
0x136b4 _dispatch_lane_barrier_sync_invoke_and_complete + 56 6 CleanerPlus
0x1674b8 FIRCLSExceptionRecord + 234 (FIRCLSException.mm:234) 7 CleanerPlus
0x167fcc FIRCLSExceptionRecordNSException + 126 (FIRCLSException.mm:126) 8
CleanerPlus 0x167110 FIRCLSTerminateHandler() + 398
(FIRCLSException.mm:398) 9 libc++abi.dylib 0x10a24 std::__terminate(void
(*)()) + 16 10 libc++abi.dylib 0x139d0 __cxa_get_exception_ptr + 34 11
libc++abi.dylib 0x1397c
__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
+ 138 12 libobjc.A.dylib 0x2bd68 objc_exception_throw + 420 13 Foundation
0x6b6d18 _userInfoForFileAndLine + 186 14 UserNotifications 0x82a0
-[UNTimeIntervalNotificationTrigger _initWithTimeInterval:repeats:] + 256
15 UserNotifications 0x8180 +[UNTimeIntervalNotificationTrigger
triggerWithTimeInterval:repeats:] + 44 16
SuperwallKit_-BCC3FC367400D_PackageProduct 0x22148c (1) suspend resume
partial function for specialized static
NotificationScheduler.scheduleNotification(_:factory:notificationCenter:) +
67 (NotificationScheduler.swift:67) 17 libswift_Concurrency.dylib 0x41c2c
swift::runJobInEstablishedExecutorContext(swift::Job*) + 416 18
libswift_Concurrency.dylib 0x42e88 swift_job_runImpl(swift::Job*,
swift::ExecutorRef) + 72 19 libdispatch.dylib 0x15be4
_dispatch_root_queue_drain + 392 20 libdispatch.dylib 0x163ec
_dispatch_worker_thread2 + 156 21 libsystem_pthread.dylib 0x1928
_pthread_wqthread + 228 22 libsystem_pthread.dylib 0x1a04 start_wqthread +
8 Thread 0 libsystem_kernel.dylib 0x9730 __workq_kernreturn + 8 1
libsystem_pthread.dylib 0x19b0 _pthread_wqthread + 364 2
libsystem_pthread.dylib 0x1a04 start_wqthread + 8
com.apple.SwiftUI.AsyncRenderer 0 libsystem_kernel.dylib 0x11d8
mach_msg2_trap + 8 1 libsystem_kernel.dylib 0xf70 mach_msg2_internal + 80 2
libsystem_kernel.dylib 0xe88 mach_msg_overwrite + 436 3
libsystem_kernel.dylib 0xcc8 mach_msg + 24 4 CoreFoundation 0x35d0c
__CFRunLoopServiceMachPort + 160 5 CoreFoundation 0x33c04 __CFRunLoopRun +
1208 6 CoreFoundation 0x33668 CFRunLoopRunSpecific + 608 7 Foundation
0x2c54c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212 8 Foundation
0x2a944 -[NSRunLoop(NSRunLoop) run] + 64 9 SwiftUI 0x7a34cc
OUTLINED_FUNCTION_101 + 24524 10 SwiftUI 0x7a3600 OUTLINED_FUNCTION_101 +
24832 11 Foundation 0xb1184 __NSThread__start__ + 732 12
libsystem_pthread.dylib 0x24d4 _pthread_start + 136 13
libsystem_pthread.dylib 0x1a10 thread_start +

**Comment by yusuftor** [comment]
Thank you! I couldn't reproduce the crash using your paywall but it does look like there may have been a notification delay <= 0 passed down in the Superwall configuration which could cause that crash. We'll look into what caused this bug but I'm adding a guard against that for the next release of the SDK. Thank you for reporting!
