### ISSUE TITLE
[BUG] Cocoapods repo not updated to 3.4.5?

### ISSUE THREAD

**Issue by lewis-smith** [superwall-me/Superwall-iOS#189]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version:
3.4.5
- iOS version(s):
n/a
- CocoaPods/Carthage version (if applicable):
1.14.3
- Xcode version:
15.1
- Devices/Simulators affected:
n/a
- Reproducible in the demo project? (Yes/No):
n/a
- Related issues:

### Describe the bug
I think cocoa pods repo isn't updated to know about newest release.

Apologies I don't publish a library myself so this isn't a strong area for me.

### Steps to reproduce
Run `pod update`

### Other Information
This shows 3.4.4: https://github.com/CocoaPods/Specs/tree/master/Specs/2/c/1/SuperwallKit

When I do `pod search SuperwallKit` I get
```
-› SuperwallKit (3.4.4)
Superwall: In-App Paywalls Made Easy
pod 'Superwallkit', '~> 3.4.4'
- Homepage: https://github.com/superwall-me/Superwall-iOS
https://github.com/superwall-me/Superwall-iOS.git
- Versions: 3.4.4, 3.4.3, 3. 4.2, 3. 4.0, 3. 3. 2, 3. 3. 1, 3. 3. 0, 3. 2. 2, 3. 2. 1, 3. 2. 0, 3. 1. 1, 3. 1. 0, 3. 0. 3, 3. 0.2, 3.0.2-xcode-12, 3.0.1, 3.0.1-xcode-12, 3.0.0,
3.0.0-xcode-12, 3.0.0-rc. 7-xcode-12, 3.0.0-rc. 7, 3.0.0-rc. 6-xcode-12, 3.0.0-rc. 6, 3.0.0-rc. 5-xcode -12, 3.0.0-rc. 5, 3.0.0-rc. 4-xcode-12, 3. 0. 0-rc. 4,
3.0.0-rc. 3-xcode-12, 3.0.0-rc. 3, 3.0.0-rc. 2-xcode-12, 3.0.0-rc. 2, 3.0.0-rc. 1-xcode-12, 3.0.0-rc. 1, 3.0.0-beta. 8-xcode-12, 3.0. 0-beta. 8,
3.0.0-beta. 7-xcode-12, 3.0.0-beta.7, 3.0.0-beta. 6-xcode-12, 3.0.0-beta.6, 3.0.0-beta. 5-xcode-12, 3.0.0-beta.5, 3.0.0-beta. 4-xcode-12, 3.0. 0-beta. 4,
3.0.0-beta. 3-xcode-12, 3.0.0-beta.3, 3.0.0-beta. 2-xcode-12, 3.0.0-beta.2, 3.0.0-beta. 1-xcode-12, 3.0.0-beta.1 [cocoapods repol
( END )
```

**Comment by yusuftor** [comment]
Ah thanks for bringing this to our attention! Looks like the session token that we use to publish to cocoapods has expired. We'll sort this out ASAP.

**Comment by yusuftor** [comment]
This should be available now, let me know if you still can't see it.

**Comment by lewis-smith** [comment]
I see it, thanks for this.
